// eslint-disable-next-line import/prefer-default-export
export const submissionConstants = {
  ADD_SUBMISSION_START: 'ADD_SUBMISSION_START',
  ADD_SUBMISSION_SUCCESS: 'ADD_SUBMISSION_SUCCESS',
  ADD_SUBMISSION_FAIL: 'ADD_SUBMISSION_FAIL',

  FETCH_SUBMISSION_START: 'FETCH_SUBMISSION_START',
  FETCH_SUBMISSION_SUCCESS: 'FETCH_SUBMISSION_SUCCESS',
  FETCH_SUBMISSION_FAIL: 'FETCH_SUBMISSION_FAIL',

  BROWSE_JUDGE_CASE_START: 'BROWSE_JUDGE_CASE_START',
  BROWSE_JUDGE_CASE_SUCCESS: 'BROWSE_JUDGE_CASE_SUCCESS',
  BROWSE_JUDGE_CASE_FAIL: 'BROWSE_JUDGE_CASE_FAIL',
};
